CREATE TABLE T1(
YEAR int,
	month int,
	sales int
)
select d1.year,(case when D1.s < D2.s then 'INCREASE' else 'DECREASE' end) as trend
FROM (SELECT YEAR,SUM(SALES) AS S FROM t1 GROUP BY YEAR) AS D1,
(SELECT YEAR,SUM(SALES)AS S FROM T1 GROUP BY YEAR AS D2
 WHERE D1.YEAR = D2.YEAR-1
 
 WITH D AS( SELECT YEAR,SUM(SALES) FROM T1 GROUP BY YEAR)
 SELECT D1.YEAR, (CASE WHEN D1.S < D2.S THEN 'INCREASE' ELSE 'DECREASE' END) AS TREND
 FROM D AS D1, D AS D2 WHERE D1.YEAR = D2.YEAR-1
